--!strict
--[[
    GameConstants
    Shared constants between server and client
]]

return {
	-- Team
	MAX_PLAYERS = 4,
	MIN_PLAYERS_TO_START = 1,

	-- Health
	MAX_HEALTH = 100,
	INCAP_HEALTH = 300,
	REVIVE_HEALTH = 30,
	MAX_INCAPS = 2,
	BLEEDOUT_RATE = 1,
	REVIVE_TIME = 5,

	-- Combat
	FRIENDLY_FIRE_MULTIPLIER = 0.5,
	MELEE_DAMAGE = 250,
	MELEE_RANGE = 3,
	SHOVE_DAMAGE = 50,
	SHOVE_COOLDOWN = 0.8,

	-- Director
	INTENSITY_PEAK_THRESHOLD = 70,
	INTENSITY_DECAY_RATE = 5,
	RELAX_DURATION_MIN = 30,
	RELAX_DURATION_MAX = 45,
	SUSTAIN_PEAK_DURATION_MIN = 3,
	SUSTAIN_PEAK_DURATION_MAX = 5,
	COMBAT_RADIUS = 30,

	-- Spawning
	COMMON_SPAWN_INTERVAL_MIN = 90,
	COMMON_SPAWN_INTERVAL_MAX = 180,
	SPECIAL_SPAWN_INTERVAL_MIN = 20,
	SPECIAL_SPAWN_INTERVAL_MAX = 40,
	MAX_ACTIVE_COMMONS = 30,
	MAX_ACTIVE_SPECIALS = 4,

	-- Performance
	ENTITY_UPDATE_RATE = 0.0625, -- 16 Hz
	NETWORK_UPDATE_RATE = 0.05, -- 20 Hz

	-- Safe Room
	SAFE_ROOM_HEAL_RATE = 5,
	SAFE_ROOM_MIN_HEALTH = 50,
}
